### ISSUE TITLE
Add interval tracking for Django logger

### ISSUE THREAD

**Issue by robfromboulder** [resurfaceio/logger-python#5]
he “interval” field is the approximate response time for the API call from the server side. This is an optional field that we’d like to have filled in by default for Django apps.

You can find examples of interval tracking in our [Express](https://github.com/resurfaceio/logger-nodejs/blob/master/lib/http_logger_for_express.js) and [Rack](https://github.com/resurfaceio/logger-ruby/blob/master/lib/resurfaceio/http_logger_for_rack.rb) loggers.

Change django.py to track intervals, like this:

    def __call__(self, request):
        start = current_millis()
        response = self.get_response(request)
        now = current_millis()
        interval = now - start
        HttpMessage.send(self.logger, request=request, response=response, None, None, now, interval)
        return response

🏅 To complete this task, you should see values for the internal column in the database. The interval column will be NULL if this is not being provided properly.

**Comment by robfromboulder** [comment]
@Anyesh -- two small adjustments if you wouldn't mind:
* Appears that interval is being calculated in seconds, please convert to milliseconds
* Interval should be encoded as a string 

Something like this?
`interval = str((time.time() - start_time) / 1000)`

Apologies as I didn't include all this detail in the original description above, my bad.

**Comment by Anyesh** [comment]
> @Anyesh -- two small adjustments if you wouldn't mind:
> 
> * Appears that interval is being calculated in seconds, please convert to milliseconds
> * Interval should be encoded as a string
> 
> Something like this?
> `interval = str((time.time() - start_time) / 1000)`
> 
> Apologies as I didn't include all this detail in the original description above, my bad.

I guess we should multiply the interval by 1000 instead of the divide to get milliseconds.

Opened a PR with the changes:
```diff
+        interval = str((time.time() - start_time) * 1000)
```

**Comment by robfromboulder** [comment]
> I guess we should multiply the interval by 1000 instead of the divide to get milliseconds.

That's what I get for doing too many things at once!  Thanks for checking my math 😀

**Comment by robfromboulder** [comment]
Integration test updated and passing
Great job @Anyesh!
